### ISSUE TITLE
Can't install using podfile - Unable to satisfy the following requirements

### ISSUE THREAD

**Issue by codecowboy** [daltoniam/SwiftHTTP#142]
I have the following podfile:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.10'
use_frameworks!

pod 'SwiftHTTP', '~> 0.9.6'
```

When I ```pod install``` I get:
```
pod install --verbose
Updating local specs repositories
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `SwiftHTTP (~> 0.9.6)` required by `Podfile`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:388:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:69:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:56:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:535:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:533:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:210:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:133:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:132:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:104:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

I would like to use the library in a Command Line Tool on OSX. I'm using XCode 7 beta 4

I should preface this by saying this is the first pod I have every tried to install using cocoapods so hopefully some kind soul can point me in the right direction.

**Comment by acmacalister** [comment]
As with your comment on #130, you need to update your pod file to point to mpclarkson swift 2.0 fork until Xcode 7 is released.

https://github.com/mpclarkson/SwiftHTTP/tree/swift-2

The Cocoapods guide can walk you through how to do this.

https://guides.cocoapods.org/using/the-podfile.html

Also if you are making a command line tool you might run into the same issue as reported on #131. If so you might have to go just the source route.

**Comment by codecowboy** [comment]
Thanks. Seems like you can't use cocoapods easily in a Swift command line tool for now so I will try just using the source.

**Comment by acmacalister** [comment]
Yeah, that seems to be what we have found as well. Not sure how much effort Apple is putting into using Swift as a command line tool these days :smile:. Let us know you if you run into anything else.

**Comment by jhmcclellandii** [comment]
They hired a new team to build this product this summer.  Woot.
