### ISSUE TITLE
Error While attempting to use Cocoapods, not sure what to do. 

### ISSUE THREAD

**Issue by Jordan-RomeroPorter** [daltoniam/SwiftHTTP#68]
### Error

```
SyntaxError - /Users/<mycomp>/Desktop/iPhone Dev/<projectFolder>/Podfile:6: syntax error, unexpected tCONSTANT, expecting end-of-input
pod 'SwiftHTTP', :git => "https://github.co...
              ^
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0/lib/cocoapods-core/podfile.rb:254:in `eval'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0/lib/cocoapods-core/podfile.rb:254:in `block in from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0/lib/cocoapods-core/podfile.rb:51:in `instance_eval'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0/lib/cocoapods-core/podfile.rb:51:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0/lib/cocoapods-core/podfile.rb:251:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0/lib/cocoapods-core/podfile.rb:251:in `from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0/lib/cocoapods-core/podfile.rb:227:in `from_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/config.rb:176:in `podfile'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:109:in `verify_podfile_exists!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:100:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

[!] Oh no, an error occurred.

It appears to have originated from your Podfile at line 6.

**Comment by daltoniam** [comment]
I just updated the README for the latest Cocoapods update. Make sure you have the `use_frameworks!` in your podfile.

https://github.com/daltoniam/SwiftHTTP#cocoapods

**Comment by daltoniam** [comment]
Got email confirmation this worked.
